[package]
name = "delta_chunk_file_sync_demo"
version = "0.1.0"
edition = "2021"


[dependencies]
notify = "6"
rusqlite = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
md5 = "0.7"
